/*
 * generated by Xtext
 */
package org.makumba.devel.plugin.eclipse.mdd;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDDRuntimeModule extends org.makumba.devel.plugin.eclipse.mdd.AbstractMDDRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		// TODO Auto-generated method stub
		return MDDValueConverter.class;
	}
}
